export {
  Dialog,
  DialogBackdrop,
  DialogClose,
  DialogContent,
  DialogCreateHandle,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogOverlay,
  DialogPanel,
  DialogPopup,
  DialogPortal,
  DialogPrimitive,
  DialogTitle,
  DialogTrigger,
  DialogViewport,
} from "@tripwire/ui/dialog"
